# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  name: CK-macOS

parameters:
  - name: hosting_regions
    type: object
    default:
      - southeastasia
      - japaneast

stages:
  - template: 'cicd/templates/stages/test.yml'

  - template: 'cicd/templates/stages/build.yml'

  - template: 'cicd/templates/stages/deploy-staging.yml'

  - template: 'cicd/templates/stages/deploy-prod.yml'
    parameters:
      hosting_regions: ${{ parameters.hosting_regions }}
