# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
parameters:
  - name: resource_group_name
    type: string
    default: cicdResourceGroup
  - name: hosting_regions
    type: object
    default:
      - southeastasia
      - japaneast
  - name: agent_pool
    type: string
    default: CK-macOS
  - name: azure_susbscription
    type: string
    default: Azure subscription 1
  - name: web_app_name
    type: string
    default: cicd-ckckck-app

trigger:
  - main

pool:
  name: CK-macOS

stages:
  - template: 'cicd/templates/stages/test.yml'

  - template: 'cicd/templates/stages/build.yml'

  - template: 'cicd/templates/stages/deploy-staging.yml'
    parameters:
      resource_group_name: ${{ parameters.resource_group_name }}
      agent_pool: ${{ parameters.agent_pool }}
      azure_susbscription: ${{ parameters.azure_susbscription }}
      web_app_name: ${{ parameters.web_app_name }}

  - template: 'cicd/templates/stages/deploy-prod.yml'
    parameters:
      resource_group_name: ${{ parameters.resource_group_name }}
      hosting_regions: ${{ parameters.hosting_regions }}
      agent_pool: ${{ parameters.agent_pool }}
      azure_susbscription: ${{ parameters.azure_susbscription }}
      web_app_name: ${{ parameters.web_app_name }}
