stages:
  - stage: build
    jobs:
      - job: buildArtifact
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'
          - script: |
              npm install
              npm run build
            displayName: 'Run build'

          # - task: ArchiveFiles@2
          #   displayName: 'Archive files'
          #   inputs:
          #     rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          #     includeRootFolder: false
          #     archiveType: zip
          #     archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          #     replaceExistingArchive: true

          # - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          #   artifact: drop
