parameters:
  - name: agent_pool
    type: string

# Not actual deploy, for POC only
stages:
  - stage: deploy_staging
    dependsOn: build
    jobs:
      - deployment: deploy_staging
        displayName: deploy staging
        pool:
          name: ${{ parameters.agent_pool }}

        environment: 'staging-env'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - script: |
                    echo 'Deploying to staging'
                    echo 'Done deployment'
