parameters:
  - name: resource_group_name
    type: string
  - name: agent_pool
    type: string
  - name: azure_susbscription
    type: string
  - name: web_app_name
    type: string

stages:
  # Not actual deploy, for POC only
  - ${{ each region in parameters.hosting_regions }}:
      - stage: deploy_prod_${{ region }}
        dependsOn: deploy_staging
        jobs:
          - deployment: deploy_prod_${{ region }}
            displayName: deploy prod ${{ region }}
            pool:
              name: ${{ parameters.agent_pool }}
            environment: 'prod-env'
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: none
                    - script: |
                        echo "Deploying app to prod ${{ region }}"
                        echo "Deployed app."
