stages:
  # Not actual deploy, for POC only
  - stage: deploy_staging
    dependsOn: build
    jobs:
      - deployment: deploy_staging
        displayName: Deploy to staging environment
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - script: |
                    echo "Deploying app to staging"
                    echo "Deployed app."
