stages:
  - stage: test
    jobs:
      - job: unittest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'
          - script: |
              npm ci
              npm run test
            displayName: 'Run unit tests'
